baseURL = "https://www.healthymind-tech.com/blog/"
languageCode = "en-us"
title = "療心智能"
theme = "hugo-theme-dream"

[params]
  author = "療心智能"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
